"""Fail-closed startup wrapper for the cache-backed RunPod worker."""

from __future__ import annotations

import json
import os
import re
import sys

from cached_models import CachedModelError, activate_cached_models


MANIFEST_PATH = "/opt/serverless/models/h3-cache-manifest.json"
HANDLER_PATH = "/opt/serverless/handler.py"
BUILD_IDENTITY_PATH = "/opt/serverless/slim-build-identity.json"
_SOURCE_COMMIT = re.compile(r"^[0-9a-f]{40}$")
_SAFE_BUILD_ID = re.compile(r"^[A-Za-z0-9._-]{1,128}$")
_SAFE_IMAGE_TAG = re.compile(r"^[a-z0-9][a-z0-9._-]{0,127}$")
_IMAGE_REPOSITORY = "ghcr.io/chrisditfort/privora-h3-runpod-worker"


def _load_build_identity() -> None:
    """Load non-secret application identity generated by the allowlisted staging step."""

    try:
        with open(BUILD_IDENTITY_PATH, encoding="utf-8") as handle:
            document = json.load(handle)
    except (OSError, json.JSONDecodeError) as error:
        raise CachedModelError(f"Could not load slim-image build identity: {error}") from error
    if not isinstance(document, dict) or document.get("schemaVersion") != 1:
        raise CachedModelError("Unsupported slim-image build identity schema")
    source_commit = document.get("sourceCommit")
    build_id = document.get("buildId")
    image_repository = document.get("imageRepository")
    image_tag = document.get("imageTag")
    if not isinstance(source_commit, str) or not _SOURCE_COMMIT.fullmatch(source_commit):
        raise CachedModelError("Invalid slim-image source commit")
    if not isinstance(build_id, str) or not _SAFE_BUILD_ID.fullmatch(build_id):
        raise CachedModelError("Invalid slim-image build id")
    if image_repository != _IMAGE_REPOSITORY:
        raise CachedModelError("Invalid slim-image repository")
    if not isinstance(image_tag, str) or not _SAFE_IMAGE_TAG.fullmatch(image_tag):
        raise CachedModelError("Invalid slim-image tag")
    if image_tag in {"latest", "multimodal-4", "code"} or image_tag.startswith("staging-"):
        raise CachedModelError("Reserved slim-image tag")
    # These values come from the allowlisted build context and are authoritative. Runtime
    # configuration cannot rewrite the source/tag identity of bytes already in the image.
    os.environ["H3_BUILD_SOURCE_COMMIT"] = source_commit
    os.environ["H3_BUILD_ID"] = build_id
    os.environ["H3_IMAGE_REPOSITORY"] = image_repository
    os.environ["H3_BUILD_IMAGE_TAG"] = image_tag


def main() -> int:
    # Set these unconditionally. A worker is not a model downloader, even if an inherited
    # library happens to import huggingface_hub or transformers later in startup.
    os.environ["HF_HUB_OFFLINE"] = "1"
    os.environ["TRANSFORMERS_OFFLINE"] = "1"
    os.environ["HF_HUB_DISABLE_TELEMETRY"] = "1"
    try:
        _load_build_identity()
        result = activate_cached_models(MANIFEST_PATH)
    except CachedModelError as error:
        print(f"FATAL cached-model activation failed: {error}", flush=True)
        return 1

    print(
        "cached-model activation OK: "
        f"repository={result.repository} revision={result.revision} "
        f"manifest={result.manifest_version} assets={result.asset_count}",
        flush=True,
    )
    os.execv(sys.executable, [sys.executable, HANDLER_PATH])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
