"""Fail-closed startup wrapper for the cache-backed RunPod worker."""

from __future__ import annotations

import json
import os
import re
import sys

from cached_models import CachedModelError, activate_cached_models


MANIFEST_PATH = "/opt/serverless/models/h3-cache-manifest.json"
HANDLER_PATH = "/opt/serverless/handler.py"
BUILD_IDENTITY_PATH = "/opt/serverless/space-build-identity.json"
_SAFE_IDENTITY = re.compile(r"^[A-Za-z0-9._:/@+-]{1,256}$")


def _load_build_identity() -> None:
    """Load non-secret application identity generated by the allowlisted staging step."""

    try:
        with open(BUILD_IDENTITY_PATH, encoding="utf-8") as handle:
            document = json.load(handle)
    except (OSError, json.JSONDecodeError) as error:
        raise CachedModelError(f"Could not load Space build identity: {error}") from error
    expected = {
        "sourceCommit": "H3_BUILD_SOURCE_COMMIT",
        "buildId": "H3_BUILD_ID",
        "spaceRepository": "H3_SPACE_REPOSITORY",
    }
    if not isinstance(document, dict) or document.get("schemaVersion") != 1:
        raise CachedModelError("Unsupported Space build identity schema")
    for field, environment_name in expected.items():
        value = document.get(field)
        if not isinstance(value, str) or not _SAFE_IDENTITY.fullmatch(value):
            raise CachedModelError(f"Invalid Space build identity field: {field}")
        os.environ.setdefault(environment_name, value)


def main() -> int:
    # Set these unconditionally. A worker is not a model downloader, even if an inherited
    # library happens to import huggingface_hub or transformers later in startup.
    os.environ["HF_HUB_OFFLINE"] = "1"
    os.environ["TRANSFORMERS_OFFLINE"] = "1"
    os.environ["HF_HUB_DISABLE_TELEMETRY"] = "1"
    try:
        _load_build_identity()
        result = activate_cached_models(MANIFEST_PATH)
    except CachedModelError as error:
        print(f"FATAL cached-model activation failed: {error}", flush=True)
        return 1

    print(
        "cached-model activation OK: "
        f"repository={result.repository} revision={result.revision} "
        f"manifest={result.manifest_version} assets={result.asset_count}",
        flush=True,
    )
    os.execv(sys.executable, [sys.executable, HANDLER_PATH])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
